; ------------------------------------------------------------------------
;
;	Win11 Widgets for Rainmeter - WiFi (medium)
;		Author   - ketamine
;		Based on - Win10 Widgets by TJ Markham (http://win10widgets.com)
;		License  - Creative Commons BY-NC-SA 4.0
;
; ------------------------------------------------------------------------

; Known bug(s):
; - See WiFi-Small.ini

[Metadata]
Name=WiFi (medium)
Author=ketamine (based on Win10 Widgets by TJ Markham)
Information=Displays the current date and time.
License=Creative Commons BY-NC-SA 4.0
Version=1.1.0

[Variables]
@Include=WiFi-Small.ini
BackgroundHeight=86
WifiIconYOffset=8


; ------------------------------------------------------------------------
; METERS - Text
; ------------------------------------------------------------------------

[WiFiSSID]
X=(#LeftPadding#+32)
MeterStyle=StyleMediumText

[ConnectedLabel]
X=(#LeftPadding#+35)
Y=0R

[Security]

[WiFiPercent]

[WiFiLabel]
MeterStyle=StyleMediumText

[NotConnectedLabel]
X=2r
