; ------------------------------------------------------------------------
;
;	Win11 Widgets for Rainmeter - CPU template
;		Author   - ketamine
;		Based on - Win10 Widgets by TJ Markham (http://win10widgets.com)
;		License  - Creative Commons BY-NC-SA 4.0
;
; ------------------------------------------------------------------------

; About:
;	Template for CPU performance monitor.

[Variables]
GraphMeasure1=MeasureCPU


; ------------------------------------------------------------------------
; MEASURES
; ------------------------------------------------------------------------

[MeasureCPU]
; Returns percent utilization of CPU.
Measure=CPU
OnUpdateAction=[!UpdateMeter Graph1][!UpdateMeter GraphBackground1][!UpdateMeter Value1]
UpdateDivider=1


; ------------------------------------------------------------------------
; METERS
; ------------------------------------------------------------------------

[Graph1]
Hidden=0

[GraphBackground1]
Hidden=0

[Top1]
Hidden=0

[Left1]
Hidden=0

[Bottom1]
Hidden=0

[Right1]
Hidden=0

[Label1]
Hidden=0

[Value1]
Hidden=0
