; ------------------------------------------------------------------------
;
;	Win11 Widgets for Rainmeter - CPU (large)
;		Author   - ketamine
;		Based on - Win10 Widgets by TJ Markham (http://win10widgets.com)
;		License  - Creative Commons BY-NC-SA 4.0
;
; ------------------------------------------------------------------------

; Known bug(s):
; - See CPU-Tiny.ini

[Metadata]
Name=CPU (large)
Author=ketamine (based on Win10 Widgets by TJ Markham)
Information=Displays CPU information.
License=Creative Commons BY-NC-SA 4.0
Version=1.1.0

[Variables]
@Include=CPU-Medium.ini
BackgroundHeight=165
GraphHeight=80
GraphTopPadding1=74


; ------------------------------------------------------------------------
; METERS
; ------------------------------------------------------------------------

[Label1]
MeterStyle=StyleBigText
X=5
Y=4

[Value1]
MeterStyle=StyleMediumText
X=0R
Y=16r
FontSize=18
FontColor=#SolidGreyText#
