; ------------------------------------------------------------------------
;
;	Win11 Widgets for Rainmeter - Date/Time (medium)
;		Author   - ketamine
;		Based on - Win10 Widgets by TJ Markham (http://win10widgets.com)
;		License  - Creative Commons BY-NC-SA 4.0
;
; ------------------------------------------------------------------------

; Known bug(s):
; - See DateTime-Large.ini

[Metadata]
Name=Date/Time (medium)
Author=ketamine (based on Win10 Widgets by TJ Markham)
Information=Displays the current date and time.
License=Creative Commons BY-NC-SA 4.0
Version=1.1.0

[Variables]
@Include=DateTime-Large.ini
BackgroundHeight=85
NumberWidth=21
ColonWidth=13


; ------------------------------------------------------------------------
; Meters
; ------------------------------------------------------------------------

[TimeHour1]
MeterStyle=StyleMediumText | StyleCenterAlign
X=(#LeftPadding#+6)

[TimeHour2]
MeterStyle=StyleMediumText | StyleCenterAlign

[TimeColon1]
MeterStyle=StyleMediumText | StyleCenterAlign
X=-11R

[TimeMinute1]
MeterStyle=StyleMediumText | StyleCenterAlign
X=-2R

[TimeMinute2]
MeterStyle=StyleMediumText | StyleCenterAlign

[TimeColon2]
MeterStyle=StyleMediumText | StyleCenterAlign
X=-11R

[TimeSecond1]
MeterStyle=StyleMediumText | StyleCenterAlign
X=-2R

[TimeSecond2]
MeterStyle=StyleMediumText | StyleCenterAlign

[Date]
Y=0R

[TimeAMPM]
MeterStyle=StyleMediumText | StyleCenterAlign
X=([TimeSecond2:X]+[TimeSecond2:W]+22)
