; ------------------------------------------------------------------------
;
;	Win11 Widgets for Rainmeter - Memory (large)
;		Author   - ketamine
;		Based on - Win10 Widgets by TJ Markham (http://win10widgets.com)
;		License  - Creative Commons BY-NC-SA 4.0
;
; ------------------------------------------------------------------------

; Known bug(s):
; - See Memory-Tiny.ini

[Metadata]
Name=Memory (large)
Author=ketamine (based on Win10 Widgets by TJ Markham)
Information=Displays memory information.
License=Creative Commons BY-NC-SA 4.0
Version=1.1.0

[Variables]
@Include=Memory-Medium.ini
BackgroundHeight=165
GraphHeight=80
GraphTopPadding2=74


; ------------------------------------------------------------------------
; METERS
; ------------------------------------------------------------------------

[Label2]
MeterStyle=StyleBigText
X=5
Y=4
Text="RAM"

[Value2]
MeterStyle=StyleMediumText
X=0R
Y=16r
FontSize=18
FontColor=#SolidGreyText#
