; ------------------------------------------------------------------------
;
;	Win11 Widgets for Rainmeter - WiFi (tiny)
;		Author   - ketamine
;		Based on - Win10 Widgets by TJ Markham (http://win10widgets.com)
;		License  - Creative Commons BY-NC-SA 4.0
;
; ------------------------------------------------------------------------

; Known bug(s):
; - See WiFi-Small.ini

[Metadata]
Name=WiFi (tiny)
Author=ketamine (based on Win10 Widgets by TJ Markham)
Information=Displays the current Wi-Fi network and signal strength.
License=Creative Commons BY-NC-SA 4.0
Version=1.1.3

[Variables]
@Include=WiFi-Small.ini
BackgroundHeight=51
WifiIconYOffset=0


; ------------------------------------------------------------------------
; MEASURES
; ------------------------------------------------------------------------

[MeasureSSID]
; WiFiPercent is positioned after WiFiSSID's width, so move it when the SSID changes.
OnChangeAction=[!UpdateMeter WiFiSSID][!UpdateMeter WiFiPercent][!Redraw]

[MeasureWiFiPercent]
; Returns the percent strength the current WiFi signal.
; Controls which signal-strength glyph is shown in the WiFi icon.
Measure=Plugin
Plugin=WiFiStatus
WiFiInfoType=Quality
OnChangeAction=[!UpdateMeter WiFiPercent]
; 0%
IfCondition=(MeasureWiFiPercent < 1) 
IfTrueAction=[!SetOption WifiIconLevel Text ""][!HideMeterGroup ConnectedTiny][!ShowMeterGroup Unconnected][!UpdateMeterGroup WifiIcon]
; 1%-25%
IfCondition2=(MeasureWiFiPercent >= 1) && (MeasureWiFiPercent <= 25)
IfTrueAction2=[!SetOption WifiIconLevel Text "[\xE872]"][!ShowMeterGroup ConnectedTiny][!HideMeterGroup Unconnected][!UpdateMeterGroup WifiIcon]
; 26%-50%
IfCondition3=(MeasureWiFiPercent >= 26) && (MeasureWiFiPercent <= 50)
IfTrueAction3=[!SetOption WifiIconLevel Text "[\xE873]"][!ShowMeterGroup ConnectedTiny][!HideMeterGroup Unconnected][!UpdateMeterGroup WifiIcon]
; 51%-75%
IfCondition4=(MeasureWiFiPercent >= 51) && (MeasureWiFiPercent <= 75)
IfTrueAction4=[!SetOption WifiIconLevel Text "[\xE874]"][!ShowMeterGroup ConnectedTiny][!HideMeterGroup Unconnected][!UpdateMeterGroup WifiIcon]
; 76%-100%
IfCondition5=(MeasureWiFiPercent >= 76)
IfTrueAction5=[!SetOption WifiIconLevel Text "[\xE701]"][!ShowMeterGroup ConnectedTiny][!HideMeterGroup Unconnected][!UpdateMeterGroup WifiIcon]


; ------------------------------------------------------------------------
; METERS - Text
; ------------------------------------------------------------------------

[WiFiSSID]
Y=(#TopPadding#+5)
Group=ConnectedTiny
ClipStringW=(#BackgroundWidth#-205)

[ConnectedLabel]
Hidden=1

[Security]
Hidden=1

[WiFiPercent]
X=([WiFiSSID:X]+[WiFiSSID:W]+2)
Y=[WiFiSSID:Y]
Group=ConnectedTiny
DynamicVariables=1

[WiFiLabel]
Y=[WiFiSSID:Y]

[NotConnectedLabel]
X=3R
Y=0r
