; ------------------------------------------------------------------------
;
;	Win11 Widgets for Rainmeter - Spotify (large)
;		Author   - ketamine
;		Based on - Win10 Widgets by TJ Markham (http://win10widgets.com)
;		License  - Creative Commons BY-NC-SA 4.0
;
; ------------------------------------------------------------------------

; Known bug(s):
; - See Spotify-Small.ini

[Metadata]
Name=Spotify (large)
Author=ketamine (based on Win10 Widgets by TJ Markham)
Information=Displays Spotify info and controls.
License=Creative Commons BY-NC-SA 4.0
Version=1.1.2

[Variables]
@Include=Spotify-Small.ini
BackgroundHeight=418
LeftPadding=10


; ------------------------------------------------------------------------
; MEASURES
; ------------------------------------------------------------------------

[MeasureCover]
;Res: 60, 85, 120, 300 or 640. Defaults to 300.
Res=640


; ------------------------------------------------------------------------
; METERS
; ------------------------------------------------------------------------

[MeterDefaultCoverBackground]
W=(#BackgroundWidth#-2)

[MeterDefaultCoverForeground]
X=181
LineStart=133
LineLength=41

[MeterTime]
X=(#BackgroundWidth#-5)

[MeterTimeOff]
X=(#BackgroundWidth#-5)

[MeterCover]
