; ------------------------------------------------------------------------
;
;	Win11 Widgets for Rainmeter - Spotify (medium, thin)
;		Author   - ketamine
;		Based on - Win10 Widgets by TJ Markham (http://win10widgets.com)
;		License  - Creative Commons BY-NC-SA 4.0
;
; ------------------------------------------------------------------------

; Known bug(s):
; - See Spotify-Small.ini

[Metadata]
Name=Spotify (medium, thin)
Author=ketamine (based on Win10 Widgets by TJ Markham)
Information=Displays Spotify info and controls.
License=Creative Commons BY-NC-SA 4.0
Version=1.1.2

[Variables]
@Include1=Spotify-Small.ini
@Include2=#@#clearContextActions.ini
BackgroundWidth=212
BackgroundHeight=317
LeftPadding=45
MediaIconSize=14
PlayIconSize=15
PrevIconX=13
PlayIconX=61
NextIconX=109
MediaIconY=37


; ------------------------------------------------------------------------
; MEASURES
; ------------------------------------------------------------------------

;[MeasureCover]
;Res: 60, 85, 120, 300 or 640. Defaults to 300.
;Res=300

[MeasurePosition]
Disabled=0

[MeasureLength]
OnChangeAction=[!UpdateMeter MeterTime2]
Disabled=0


; ------------------------------------------------------------------------
; METERS - Previous Track
; ------------------------------------------------------------------------

[PreviousButton]
X=#LeftPadding#
Y=(#BackgroundHeight#-51)
W=26
H=28

; ------------------------------------------------------------------------
; METERS - Play/Pause Circle
; ------------------------------------------------------------------------

[PlayPauseCircle]
; Shows the circle of the play/pause button when Spotify is open.
; Acts as play/pause button; plays/pauses current Spotify track when clicked.
Meter=Roundline
X=([PreviousButton:X]+39)
Y=([PreviousButton:Y]-8)
H=44
W=44
LineStart=22
LineLength=20.8

[PlayPauseCircleOff]
X=[PlayPauseCircle:X]
Y=[PlayPauseCircle:Y]
H=[PlayPauseCircle:H]
W=[PlayPauseCircle:W]
LineStart=22
LineLength=20.8


; ------------------------------------------------------------------------
; METERS - Next Track
; ------------------------------------------------------------------------

[NextButton]
X=([PlayPauseCircle:X]+57)
Y=([PlayPauseCircle:Y]+8)
W=26
H=28

; ------------------------------------------------------------------------
; METERS - Cover
; ------------------------------------------------------------------------

[MeterDefaultCoverBackground]
W=(#BackgroundWidth#-2)

[MeterDefaultCoverForeground]
X=106
LineStart=78
LineLength=25

[MeterCover]


; ------------------------------------------------------------------------
; METERS - Text
; ------------------------------------------------------------------------

[MeterTime]
MeterStyle=StyleTinyTextSpotify | StyleLeftAlign
X=5
Y=272
Text="%1"
Group=SpotifyOn

[MeterTime2]
; Shows length of currently playing Spotify track.
Meter=String
MeterStyle=StyleTinyTextSpotify
MeasureName=MeasureLength
X=(#BackgroundWidth#-5)
Y=[MeterTime:Y]
Group=SpotifyOn
Text="%1"
UpdateDivider=-1
Hidden=1

[MeterTimeOff]
MeterStyle=StyleTinyTextSpotify | StyleLeftAlign
X=5
Text="0:00"
Group=SpotifyOff

[MeterTime2Off]
; Shows "0:00" when Spotify is closed.
Meter=String
MeterStyle=StyleTinyTextSpotify
X=(#BackgroundWidth#-5)
Y=[MeterTime:Y]
Group=SpotifyOff
Text="0:00"
UpdateDivider=-1
Hidden=1

[MeterTrack]
MeterStyle=StyleSmallTextSpotify | StyleCenterAlign
X=(#BackgroundWidth#/2)
Y=217
ClipString=2
ClipStringW=(#BackgroundWidth#-10)

[MeterArtist]
MeterStyle=StyleSmallTextSpotify | StyleCenterAlign
ClipString=2
ClipStringW=(#BackgroundWidth#-10)

[MeterTrackOff]
MeterStyle=StyleSmallTextSpotify | StyleCenterAlign

[MeterArtistOff]
MeterStyle=StyleSmallTextSpotify | StyleCenterAlign
