; ------------------------------------------------------------------------
;
;	Win11 Widgets for Rainmeter - Date/Time (small)
;		Author   - ketamine
;		Based on - Win10 Widgets by TJ Markham (http://win10widgets.com)
;		License  - Creative Commons BY-NC-SA 4.0
;
; ------------------------------------------------------------------------

; Known bug(s):
; - See DateTime-Large.ini

[Metadata]
Name=Date/Time (small)
Author=ketamine (based on Win10 Widgets by TJ Markham)
Information=Displays the current date and time.
License=Creative Commons BY-NC-SA 4.0
Version=1.1.0

[Variables]
@Include=DateTime-Medium.ini
BackgroundHeight=68
NumberWidth=12
ColonWidth=8


; ------------------------------------------------------------------------
; Measures
; ------------------------------------------------------------------------

[MeasureHour1]
; Changes X value for TimeHour2 based on whether the hour has one or two digits.
IfTrueAction=[!ShowMeter TimeHour1][!SetOption TimeHour2 X -4R]


; ------------------------------------------------------------------------
; Meters
; ------------------------------------------------------------------------

[TimeHour1]
X=(#LeftPadding#+4)
FontSize=11

[TimeHour2]
FontSize=11

[TimeColon1]
X=-6R
FontSize=11

[TimeMinute1]
FontSize=11

[TimeMinute2]
X=-4R
FontSize=11

[TimeColon2]
X=-6R
FontSize=11

[TimeSecond1]
FontSize=11

[TimeSecond2]
X=-4R
FontSize=11

[Date]
Y=0R

[TimeAMPM]
X=([TimeSecond2:X]+[TimeSecond2:W]+13)
FontSize=11
W=27
