; ------------------------------------------------------------------------
;
;	Win11 Widgets for Rainmeter - Disk (small)
;		Author   - ketamine
;		Based on - Win10 Widgets by TJ Markham (http://win10widgets.com)
;		License  - Creative Commons BY-NC-SA 4.0
;
; ------------------------------------------------------------------------

; Known bug(s):
; - See Disk-Tiny.ini

[Metadata]
Name=Disk (small)
Author=ketamine (based on Win10 Widgets by TJ Markham)
Information=Displays disk information.
License=Creative Commons BY-NC-SA 4.0
Version=1.1.3

[Variables]
@Include=Disk-Tiny.ini
BackgroundHeight=91
GraphWidth=339
GraphTopPadding3=40


; ------------------------------------------------------------------------
; METERS
; ------------------------------------------------------------------------

[Label3]
X=10
Y=10

[Value3]
FontSize=11
X=5R
Y=0r

[HDSelectBackground]

[A:]

[B:]

[C:]

[D:]

[E:]

[F:]

[G:]

[H:]

[I:]

[J:]

[K:]

[L:]

[M:]

[N:]

[O:]

[P:]

[Q:]

[R:]

[S:]

[T:]

[U:]

[V:]

[W:]

[X:]

[Y:]

[Z:]
