; ------------------------------------------------------------------------
;
;	Win11 Widgets for Rainmeter - WiFi (large)
;		Author   - ketamine
;		Based on - Win10 Widgets by TJ Markham (http://win10widgets.com)
;		License  - Creative Commons BY-NC-SA 4.0
;
; ------------------------------------------------------------------------

; Known bug(s):
; - See WiFi-Small.ini

[Metadata]
Name=WiFi (large)
Author=ketamine (based on Win10 Widgets by TJ Markham)
Information=Displays the current date and time.
License=Creative Commons BY-NC-SA 4.0
Version=1.1.2

[Variables]
@Include=WiFi-Small.ini
BackgroundHeight=120
WifiIconYOffset=22
WifiIconSize=20


; ------------------------------------------------------------------------
; METERS - Text
; ------------------------------------------------------------------------

[WiFiSSID]
X=(#LeftPadding#+30)
MeterStyle=StyleBigText

[ConnectedLabel]
X=(#LeftPadding#+35)
Y=-6R

[Security]

[WiFiPercent]

[WiFiLabel]
MeterStyle=StyleBigText

[NotConnectedLabel]
X=10r
