; ------------------------------------------------------------------------
;
;	Win11 Widgets for Rainmeter - CPU (small)
;		Author   - ketamine
;		Based on - Win10 Widgets by TJ Markham (http://win10widgets.com)
;		License  - Creative Commons BY-NC-SA 4.0
;
; ------------------------------------------------------------------------

; Known bug(s):
; - See CPU-Tiny.ini

[Metadata]
Name=CPU (small)
Author=ketamine (based on Win10 Widgets by TJ Markham)
Information=Displays CPU information.
License=Creative Commons BY-NC-SA 4.0
Version=1.1.0

[Variables]
@Include=CPU-Tiny.ini
BackgroundHeight=91
GraphWidth=339
GraphTopPadding1=40


; ------------------------------------------------------------------------
; METERS
; ------------------------------------------------------------------------

[Label1]
X=10
Y=10

[Value1]
FontSize=11
X=5R
Y=0r
