; ------------------------------------------------------------------------
;
;	Win11 Widgets for Rainmeter - Performance Combo (thin)
;		Author   - ketamine
;		Based on - Win10 Widgets by TJ Markham (http://win10widgets.com)
;		License  - Creative Commons BY-NC-SA 4.0
;
; ------------------------------------------------------------------------

; Known bug(s):
; - See Combo.ini

[Metadata]
Name=Performance Combo (thin)
Author=ketamine (based on Win10 Widgets by TJ Markham)
Information=Displays CPU, memory, disk, network, and GPU information.
License=Creative Commons BY-NC-SA 4.0
Version=1.1.2

[Variables]
@Include=Combo.ini
BackgroundHeight=262
BackgroundWidth=212
FirstColumnLeftPadding=11
FirstRowTopPadding=11
SecondRowTopPadding=61
ThirdRowTopPadding=111
FourthRowTopPadding=161
FifthRowTopPadding=211
; CPU Variables
GraphLeftPadding1=#FirstColumnLeftPadding#
GraphTopPadding1=#FirstRowTopPadding#
; Memory Variables
GraphLeftPadding2=#FirstColumnLeftPadding#
GraphTopPadding2=#SecondRowTopPadding#
; Disk Variables
GraphLeftPadding3=#FirstColumnLeftPadding#
GraphTopPadding3=#ThirdRowTopPadding#
; Network Variables
GraphLeftPadding4=#FirstColumnLeftPadding#
GraphTopPadding4=#FourthRowTopPadding#
; GPU Variables
GraphLeftPadding5=#FirstColumnLeftPadding#
GraphTopPadding5=#FifthRowTopPadding#
; Extra disk layouts (by number of extra drives; see extraDisksTemplate.ini)
ExtraDiskLayout0=net=11,161 gpu=11,211 size=212,262
ExtraDiskLayout1=d=11,161 net=11,211 gpu=11,261 size=212,312
ExtraDiskLayout2=d=11,161|11,211 net=11,261 gpu=11,311 size=212,362
ExtraDiskLayout3=d=11,161|11,211|11,261 net=11,311 gpu=11,361 size=212,412
ExtraDiskLayout4=d=11,161|11,211|11,261|11,311 net=11,361 gpu=11,411 size=212,462
ExtraDiskLayout5=d=11,161|11,211|11,261|11,311|11,361 net=11,411 gpu=11,461 size=212,512


; ------------------------------------------------------------------------
; METERS - Disk Selector
; ------------------------------------------------------------------------

[HDSelectBackground]

[A:]
X=37
Y=60

[B:]

[C:]

[D:]

[E:]

[F:]

[G:]

[H:]
X=([A::X]+11)
Y=([A::H]+[A::Y]+1)
Group=HDSelect | NewLine
DynamicVariables=1

[I:]

[J:]

[K:]

[L:]

[M:]

[N:]
X=1R
Y=0r
Group=HDSelect

[O:]
X=([H::X]+11)
Y=([H::H]+[H::Y]+1)
Group=HDSelect | NewLine
DynamicVariables=1

[P:]

[Q:]

[R:]

[S:]

[T:]

[U:]

[V:]
X=([P::X]+11)
Y=([O::H]+[O::Y]+1)
Group=HDSelect | NewLine
DynamicVariables=1

[W:]

[X:]

[Y:]

[Z:]
