; ------------------------------------------------------------------------
;
;	Win11 Widgets for Rainmeter - Performance Combo (all)
;		Author   - ketamine
;		Based on - Win10 Widgets by TJ Markham (http://win10widgets.com)
;		License  - Creative Commons BY-NC-SA 4.0
;
; ------------------------------------------------------------------------

; Known bug(s):
; - See CPU-Tiny.ini, Memory-Tiny.ini, Disk-Tiny.ini, and 
;	Network-Tiny.ini

[Rainmeter]
Update=1000

[Metadata]
Name=Performance Combo (all)
Author=ketamine (based on Win10 Widgets by TJ Markham)
Information=Displays CPU, memory, disk, network, and GPU information.
License=Creative Commons BY-NC-SA 4.0
Version=1.1.2

[Variables]
@Include1="#@#Performance Templates\performanceTemplateX4.ini"
@Include2="#@#Performance Templates\cpuTemplate.ini"
@Include3="#@#Performance Templates\memoryTemplate.ini"
@Include4="#@#Performance Templates\diskTemplate.ini"
@Include5="#@#Performance Templates\networkTemplate.ini"
@Include6="#@#Performance Templates\gpuTemplate.ini"
@Include7="#@#Performance Templates\extraDisksTemplate.ini"
CoreFilePath=""#CURRENTPATH#Combo.ini""
BackgroundHeight=162
AutoBorder=1
FirstColumnLeftPadding=11
SecondColumnLeftPadding=160
FirstRowTopPadding=11
SecondRowTopPadding=61
ThirdRowTopPadding=111
; CPU Variables
GraphLeftPadding1=#FirstColumnLeftPadding#
GraphTopPadding1=#FirstRowTopPadding#
; Memory Variables
GraphLeftPadding2=#SecondColumnLeftPadding#
GraphTopPadding2=#FirstRowTopPadding#
; Disk Variables
GraphLeftPadding3=#FirstColumnLeftPadding#
GraphTopPadding3=#SecondRowTopPadding#
; Network Variables
GraphLeftPadding4=160
GraphTopPadding4=111
; GPU Variables
GraphLeftPadding5=11
GraphTopPadding5=111
; Extra disk layouts (by number of extra drives; see extraDisksTemplate.ini)
ExtraDiskLayout0=net=160,61 gpu=11,111 size=361,162
ExtraDiskLayout1=d=160,61 net=160,111 gpu=11,111 size=361,162
ExtraDiskLayout2=d=160,61|11,161 net=160,111 gpu=11,111 size=361,212
ExtraDiskLayout3=d=160,61|11,161|160,161 net=160,111 gpu=11,111 size=361,212
ExtraDiskLayout4=d=160,61|11,161|160,161|11,211 net=160,111 gpu=11,111 size=361,262
ExtraDiskLayout5=d=160,61|11,161|160,161|11,211|160,211 net=160,111 gpu=11,111 size=361,262
ExtraDisks=D:
ExtraDisksFile=Combo.ini
XDX1=160
XDY1=61
BackgroundWidth=361


; ------------------------------------------------------------------------
; METERS - Disk Selector
; ------------------------------------------------------------------------

[HDSelectBackground]

[A:]

[B:]

[C:]

[D:]

[E:]

[F:]

[G:]

[H:]

[I:]

[J:]

[K:]

[L:]

[M:]

[N:]

[O:]

[P:]

[Q:]

[R:]

[S:]

[T:]

[U:]

[V:]

[W:]

[X:]

[Y:]

[Z:]
